### ISSUE TITLE
Auto-generated Swagger.json from the Backend does not work with API Management

### ISSUE THREAD

**Issue by robinmanuelthiel** [Microsoft/app-innovation-workshop#6]
The ASP.NET Core Backend is generating a Swagger.json file using [Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore).

![screen shot 2018-09-24 at 12 45 25](https://user-images.githubusercontent.com/5874465/45948305-be940880-bff7-11e8-94b8-df4642e48995.png)

When importing this Swagger File into Azure API Management, it is throwing errors! As a workaround, we currently have provided fixed JSON files as Assets, but it would be nice, if participants could just import that Swagger.json URL.

**Comment by JimPaine** [comment]
@robinmanuelthiel if you are happy with the approach in #9 I will clean up the documentation and remove the static files

**Comment by robinmanuelthiel** [comment]
Sounds good. I left some requests for clarification in the code review! Thanks for your contribution!
